### ISSUE TITLE
Add support *

### ISSUE THREAD

**Issue by zhuharev** [go-macaron/switcher#1]
What you think about support *
i.e. `*example.com` or `*.example.com` ?

**Comment by unknwon** [comment]
Thanks your feedback!

It could be done, but just think is supporting a regexp match necessary(just a thought)?

**Comment by unknwon** [comment]
Hi, code has been pushed to `master` and you can help test!

**Comment by zhuharev** [comment]
@Unknwon, thank for quick response, I'm going to test it at home

**Comment by unknwon** [comment]
No problem.
